Database.langs = {
	fr: {
			"GET_GOLD": "Vous obtenez 7 Or",
			"GET_GOLD_2": "Vous obtenez 3 Or",
			"GET_GOLD_3": "Vous obtenez 5 Or",
			"PROHIBITED": "Entrée interdite",
			"YEAHHHH": "Yeahhhhh",
			"SPEND": "Je vais passer la journée à enlever les mauvaises \nherbes",
			"HELP_US": "Aides-nous, ma fille a été kidnappée et \nemprisonnée dans les catacombes à l'est du village",
			"WARRIOR": "Je suis une guerrière sans arme. Il me semble \n qu'il y a une épée dans la grotte du village",
			"LEAVE": "Si tu quittes le village, soit vigilant !",
			"CALM": "Le village est calme",
			"BORED": "Je m'ennnuie",
			"COURAGE": "Tu mérites une bonne récompense pour ton courage",
			"MONEY": "Ne dépense pas l'argent donné inutilement !",
			"NEED_SWORD": "Tu as besoin d'une épée avant de quitter le village",
			"SWORD": "Vous recevez une épée",
			"PASS": "Tu peux passer seulement si tu me donnes 15 Or !",
			"GIVE_ME": "Domme moi 15 Or",
			"YOU_LOSE": "Vous perdez 15 Or",
			"TY": "Merci de m'avoir sauvé !"
		},
	en: {
			"GET_GOLD": "You get 7 Gold",
			"GET_GOLD_2": "You get 3 Gold",
			"GET_GOLD_3": "You get 5 Gold",
			"PROHIBITED": "Entry prohibited",
			"YEAHHHH": "Yeahhhhh",
			"SPEND": "I'll spend the day removing weeds",
			"HELP_US": "Help us, my daughter was kidnapped and imprisoned \nin the catacombs to the east of the village",
			"WARRIOR": "I am a warrior without a weapon. It seems \nhe has a sword in a cave in the village",
			"LEAVE": "If you leave the city, be vigilant !",
			"CALM": "The city is calm.",
			"BORED": "I'm bored",
			"COURAGE": "You deserve a good reward for your courage",
			"MONEY": "Not spend money unnecessarily given !",
			"NEED_SWORD": "You need to have a sword before leaving the village",
			"SWORD": "You receive a sword",
			"PASS": "You can pass only if you give me 15 Or !",
			"GIVE_ME": "Give me 15 Gold",
			"YOU_LOSE": "You lose 15 Gold",
			"TY": "Thank you for saving me !"
		}
};